### ISSUE TITLE
Conditional post w.r.t. branch

### ISSUE THREAD

**Issue by rmitsch** [ravsamhq/notify-slack-action#106]
Very useful action, thanks! I was wondering whether it's possible to post to Slack only if the workflow is triggered for a certain branch, e. g. `main`?

**Comment by ravgeetdhillon** [comment]
@rmitsch You can fix this issue by adding an `if` condition to the step that calls this action. For more details on implementation, check out this [discussion](https://github.com/orgs/community/discussions/25216).

**Comment by ravgeetdhillon** [comment]
@rmitsch Were you able to solve your issue? If not, you can check out the [documentation](https://github.com/ravsamhq/notify-slack-action/blob/master/README.md#running-a-workflow-only-on-the-specified-branch). I am sure it will solve your issue.

I am going to close this issue but be free to open it if your issue isn't resolved.
