### ISSUE TITLE
Only notify when MAIN branch fails during the build

### ISSUE THREAD

**Issue by EllieSager-Forte** [ravsamhq/notify-slack-action#115]
Hello!
I don't see a way to specify that we only want to receive notifications when the build that fails is in the _main_ (master) and not in a feature branch.
Do you have such an option?
If not, how hard would it be to add it?

**Comment by ravgeetdhillon** [comment]
@EllieSager-Forte Kindly check the discussion on #106 to resolve your issue.

In short, you can fix this issue by adding an if condition to the step that calls this action. For more details on implementation, check out this [discussion](https://github.com/orgs/community/discussions/25216).

**Comment by ravgeetdhillon** [comment]
@EllieSager-Forte Were you able to solve your issue? If not, you can check out the [documentation](https://github.com/ravsamhq/notify-slack-action/blob/master/README.md#running-a-workflow-only-on-the-specified-branch). I am sure it will solve your issue.

I am going to close this issue but be free to open it if your issue isn't resolved.
