### ISSUE TITLE
Notify on failure, with only the main branch.

### ISSUE THREAD

**Issue by idomic** [ravsamhq/notify-slack-action#117]
Hi, saw this [issue](https://github.com/ravsamhq/notify-slack-action/issues/37) and another on the `ref/heads/main`.
My usecase is running only on main, and always() (if that fails on an earlier tasks).

Is this possible?
I tried adding `if: always() && ${{ github.ref == 'refs/heads/main' }}` but that doesn't solve it.

**Comment by Vanals** [comment]
I would like to use it only for this specific case too

**Comment by ravgeetdhillon** [comment]
Were you able to solve your issue? If not, you can check out the [documentation](https://github.com/ravsamhq/notify-slack-action/blob/master/README.md#running-a-workflow-only-on-the-specified-branch). I am sure it will solve your issue.

I am going to close this issue but be free to open it if your issue isn't resolved.
