### ISSUE TITLE
Request for workflow_url in message

### ISSUE THREAD

**Issue by hovaesco** [ravsamhq/notify-slack-action#12]
Hi 👋

I have a small request, could you please add support for having GHA workflow_url in message as var available for formatting? 

In addition, I might just have identified a bug in {repo_url} that points out or `refs/heads` instead of master. Due to that I cannot navigate through repo and need to change a branch manually.  

That would be appreciated. 
Thanks,
Przemek

**Comment by ravgeetdhillon** [comment]
This issue has been resolved in release [1.4.0](https://github.com/ravsamhq/notify-slack-action/releases/tag/1.4.0).

**Comment by hovaesco** [comment]
@ravgeetdhillon thanks!
