### ISSUE TITLE
Upgrade to Node18

### ISSUE THREAD

**Issue by mkukawski** [ravsamhq/notify-slack-action#120]
It seem to use Node 16 still

**Comment by jsmatfess** [comment]
I wanted to +1 this @ravgeetdhillon. GitHub is deprecating Node 16 actions and recommending that they be upgraded to Node 20. We've started getting warnings on our workflows.

https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20

**Comment by ravgeetdhillon** [comment]
This has been fixed in https://github.com/ravsamhq/notify-slack-action/pull/124.
