### ISSUE TITLE
Upgrade to node20

### ISSUE THREAD

**Issue by hxyannay** [ravsamhq/notify-slack-action#123]
Hey there,
this action still uses node16, which is soon to be deprecated and started raising github warnings.
Would love if you could update it to use node20.
Thanks!

**Comment by fubha** [comment]
@ravgeetdhillon seems it's still not resolved. I am using the latest version `2.4.0`, but I am still getting a warning.
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: ravsamhq/notify-slack-action@2.4.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
