### ISSUE TITLE
Error with notify-slac-action and pylint 2.8.3

### ISSUE THREAD

**Issue by hhslepicka** [ravsamhq/notify-slack-action#14]
Hi,

The latest commit ( https://github.com/ravsamhq/notify-slack-action/commit/a80d8ae5e659a5c45e3a1010509ed9857e61a858 ) introduced an issue that is preventing the master version of this action to be installed and used.
More details here: https://github.com/bmad-sim/bmad_distribution/runs/2749669252?check_suite_focus=true#step:2:108

It is an incompatibility between astroid and pylint:
```
      The user requested astroid==2.5.7
      pylint 2.8.3 depends on astroid==2.5.6
```

**Comment by ravgeetdhillon** [comment]
Hi @hhslepicka 

It is recommended to use `v1` of the action. Use like this `ravsamhq/notify-slack-action@v1`.

**Comment by hhslepicka** [comment]
@ravgeetdhillon I switched my pipeline to the tag before posting. I just opened the issue here so it can be fixed for master.

Thank you
