### ISSUE TITLE
Unable to run the actions getting docker error

### ISSUE THREAD

**Issue by ashokelixir** [ravsamhq/notify-slack-action#15]
Build container for action use: '/home/runner/work/_actions/ravsamhq/notify-slack-action/master/Dockerfile'.
  /usr/bin/docker build -t 8a33c1:65b5d5e5223c45dbaa102693b1c509c8 -f "/home/runner/work/_actions/ravsamhq/notify-slack-action/master/Dockerfile" "/home/runner/work/_actions/ravsamhq/notify-slack-action/master"

ERROR: Cannot install -r requirements.txt (line 10) and astroid==2.5.7 because these package versions have conflicting dependencies.

**Comment by ravgeetdhillon** [comment]
Hi @ashokelixir 

It is recommended to use v1 of the action.

Change from `ravsamhq/notify-slack-action@master` to `ravsamhq/notify-slack-action@v1`.
