### ISSUE TITLE
Slack notification not working

### ISSUE THREAD

**Issue by vinothgitkumar** [ravsamhq/notify-slack-action#22]
I have tried to send the slack notification with slack webhook but it stopped working from last week. My action code is as below.

      - name: slack-notify
        uses: ravsamhq/notify-slack-action@v1
        if: always()
        with:
          status: Notification
          notification_title: 'New code in pull-request is {status_message} in SonarQube analysis, need review for pull request approval'
          message_format: '{emoji} Workflow *{workflow}* has {status_message} in <{repo_url}|{repo}>. Static Code Analysis results are in URL: https://sonarcloud.io/dashboard?id=${{ github.event.repository.name }}&branch=${GITHUB_REF#refs/heads/}'
        env:  
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

**Comment by ravgeetdhillon** [comment]
Hi @vinothgitkumar. You are using the action in the wrong way.

`status` key needs to be as follows:

```yml
status: ${{ job.status }}
```

**Comment by ravgeetdhillon** [comment]
I am assuming this issue has been solved.
