### ISSUE TITLE
Security warnings with pip.

### ISSUE THREAD

**Issue by kary-ajrj** [ravsamhq/notify-slack-action#23]
<img width="946" alt="Screenshot 2021-10-12 at 15 01 41" src="https://user-images.githubusercontent.com/7961532/136931214-61255c77-4c71-410e-af04-e5a10dfaee2a.png">

Notice in the 4th step out of 9, it says that pip :
1. Should not have root access.
2. Used version of pip is outdated.

**Comment by ravgeetdhillon** [comment]
Hi @kary-ajrj. Thanks for the head. I just want to know if the action is working for you as intended despite the warnings?
