### ISSUE TITLE
Improve message

### ISSUE THREAD

**Issue by andrii29** [ravsamhq/notify-slack-action#3]
hi,
can you add few improvements to this action?
- be able to replace default message "New Github Action Run" with "{workflow} ({status_message})" (or any other via with.pretext?)
- make **{workflow}** in message bold
- allow to mention slack users (via with.mentions)
- add url to this action , e.g. https://github.com/user/repo/actions/runs/72943275 or at least https://github.com/user/repo/actions/workflows/tests.yml

Regard,
Andrii

**Comment by ravgeetdhillon** [comment]
Hi @andrii29,

I will work on these aspects this weekend. Thanks.

**Comment by andrii29** [comment]
hi,
one more improvement)
- allow to mention slack users (via with.mentions)
It would be nice to be able to send mentions only on errors or success (via with.mentions_motify_when?).

For example,
i want to send notifications always, but mentions only on errors.

TY!

**Comment by ravgeetdhillon** [comment]
Except 
- add url to this action , e.g. https://github.com/user/repo/actions/runs/72943275 or at least https://github.com/user/repo/actions/workflows/tests.yml

Everything has been solved.

**Comment by ravgeetdhillon** [comment]
This issue has been resolved in release [1.2.0](https://github.com/ravsamhq/notify-slack-action/releases/tag/1.2.0).

**Comment by andrii29** [comment]
hi, 
TY!

one more improvement.
Now without specify mention and mention_when I will get message like this
![image](https://user-images.githubusercontent.com/31315876/114349748-f8ef3200-9b70-11eb-96ea-08c71681a19d.png)
consider update if statement https://github.com/ravsamhq/notify-slack-action/blob/master/main.py#L98
`and mention != ''`

**Comment by andrii29** [comment]
also, please allow to mention teams
https://stackoverflow.com/questions/54284389/mention-users-group-via-slack-api

**Comment by andrii29** [comment]
one more feature)
- tag users (or groups) in new line

**Comment by ravgeetdhillon** [comment]
Hi @andrii29 .

Please open these requests as a new issue. Thanks for understanding.
