### ISSUE TITLE
Is it possible to notify/mention a user dynamically?

### ISSUE THREAD

**Issue by smetroid** [ravsamhq/notify-slack-action#31]
Hello,

Would it be possible to notify/mention a user dynamically?  The user who started the job?

Thanks,

--
Enrique

**Comment by ravgeetdhillon** [comment]
Hey @smetroid,

The thing is to notify that user you need their Slack User Id. You need a way to map the `${{ github.actor }}` to the valid Slack User Id.

**Comment by ravgeetdhillon** [comment]
Since this is not related to the action but some external logic, so I'm closing this.
