### ISSUE TITLE
Job status shows always as success in Composite action 

### ISSUE THREAD

**Issue by asrar7787** [ravsamhq/notify-slack-action#32]
Hi,

I am using this action inside a composite action. When I pass the job status from the triggering workflow to the composite action, it always comes up as success.

Is there any way to set/get job status correctly when using this action inside a composite action?

Thanks

**Comment by ravgeetdhillon** [comment]
Hi @asrar7787,

Can you please share some code snippet for better understanding?

**Comment by jodosha** [comment]
Hey, I had the same problem.
Here's my configuration: https://github.com/hanami/controller/blob/6f1ab299d8cfe2da50198c5fef3edc0645e858b9/.github/workflows/ci.yml

The trigger was a push to the `main` Git branch.
I've got a notification on Slack that CI passed, but it didn't.


![Screen Shot 2022-02-08 at 10 04 40](https://user-images.githubusercontent.com/5089/152953737-3b55f235-6506-4ed2-8354-86dccde5bf91.png)

![Screen Shot 2022-02-08 at 10 05 39](https://user-images.githubusercontent.com/5089/152953883-49e7198d-3f45-490b-bfc9-ef327da5decf.png)

**Comment by ravgeetdhillon** [comment]
This is related to #37 so going to close this as well.
