### ISSUE TITLE
Publish a docker image

### ISSUE THREAD

**Issue by mpcusack-color** [ravsamhq/notify-slack-action#33]
Would it be possible to publish a docker image so using this action won't require building the docker image each time?

Thanks for supporting this GHA!

**Comment by ravgeetdhillon** [comment]
I'm not well versed with Docker to be honest. If you can submit aPR, I'd be happy to take a look.

**Comment by ravgeetdhillon** [comment]
Please check #38.

**Comment by ravgeetdhillon** [comment]
Closing this issue in the favour of #38.
