### ISSUE TITLE
Support mention_groups: !channel

### ISSUE THREAD

**Issue by svengau** [ravsamhq/notify-slack-action#35]
Hey and thanks for your nice plugin. 

I would like to mention all users in a channel like `@channel` in slack. this could be done programmatically using `<!channel>`. The current implementation of mention_groups appends `!subteam^` to the group name. It would be great if it only appends if the group doesn't start with `!`

**Comment by ravgeetdhillon** [comment]
@svengau Thank you so much for this feature request and your recommendations.

I've just released a new version [1.8.0](https://github.com/ravsamhq/notify-slack-action/releases/tag/1.8.0). Now you can mention the channel by doing:

```yaml
mention_groups: 'SAZ94GDB8,!channel'
```

Let me know if this solves your issue.
