### ISSUE TITLE
`notify_when: failure` doesn't send the message to Slack in case of failure

### ISSUE THREAD

**Issue by jodosha** [ravsamhq/notify-slack-action#37]
Hey thanks for this project.

I had `notify_when: failure` to avoid being flooded by several OSS repositories that are run daily via GitHub Actions cron.
So I want only to know when scheduled CI fails.

Yesterday, the cron scheduled GHA failed, but I didn't get any notification on Slack.

Here's my configuration: https://github.com/hanami/controller/blob/f2c1844a2ee57aeeba4e8641006349e0b23c732d/.github/workflows/ci.yml

**Comment by ravgeetdhillon** [comment]
@jodosha You need to add the notify slack step at the very last so that if any of the preceding steps fail, Github Actions knows to run the step specified with `if: always()`.

Let me know if this solution works for you.

**Comment by ravgeetdhillon** [comment]
@jodosha I hope this solved your issue. Let me know if you have any questions. I'm closing this for now.

**Comment by jodosha** [comment]
@ravgeetdhillon Hey yes, it works! Thanks.
I waited for a failure on our CI before to give this confirmation. 🙂
