### ISSUE TITLE
Migrate Action to Javascript from Python

### ISSUE THREAD

**Issue by ravgeetdhillon** [ravsamhq/notify-slack-action#38]
The current implementation uses Python and Docker is required for building the action. Docker builds take about 15-20s for each build which is too much as compared to the actions written in Javascript (1-2s).

> Less time on builds means more money savings.

I'll try to migrate this action to Javascript and get rid of the Docker builds and release the new action as **v2**.

If anyone has a better alternative/suggestion, please comment below. I'd be more than happy to take your advice.

Thanks.

**Comment by yermukhanbet** [comment]
Hey man! Thanks for the great work!
Was wondering if there are any updates on possibly adding macOS run?

**Comment by ravgeetdhillon** [comment]
[v2](https://github.com/ravsamhq/notify-slack-action/releases/tag/v2) released. 🎉

To use v2, just change the action version from v1 to v2:

```yml
- uses: ravsamhq/notify-slack-action@v1
# to
- uses: ravsamhq/notify-slack-action@v2
```

**Comment by markstos** [comment]
Thanks for this! I found I had hundreds of leftover Docker images due to this plugin, and this rewrite is the best solution to that problem too!
