### ISSUE TITLE
Request for "{branch_url}" OR usage of environment variables in the message_format

### ISSUE THREAD

**Issue by gabiganam** [ravsamhq/notify-slack-action#39]
I think this variable will be very useful.
It is basically:
{repo_url}/tree/{branch}, just need to remove the "refs/heads/" prefix from the branch variable.

Alternatively, if I can use environment variables, it will also solve my issue, I could construct the URL with my "CI_BRANCH" env var, like so:
`message_format: 'Branch <{repo_url}/tree/$CI_BRANCH|{branch}> on commit <{commit_url}|{commit_sha}>'`

**Comment by ravgeetdhillon** [comment]
@gabiganam `branch_url` variable is now available in [v2.2.0](https://github.com/ravsamhq/notify-slack-action/releases/tag/2.2.0). For more details, checkout the [README](https://github.com/ravsamhq/notify-slack-action#readme).
