### ISSUE TITLE
Possible to use `@here` instead of `@channel`?

### ISSUE THREAD

**Issue by drewhemm** [ravsamhq/notify-slack-action#43]
Would be nice if it were possible to notify only active members in a channel using [@here](https://slack.com/intl/en-gb/help/articles/202009646-Notify-a-channel-or-workspace#u64here), instead of [@channel](https://slack.com/intl/en-gb/help/articles/202009646-Notify-a-channel-or-workspace#u64channel), which will notify people who are set to away:

https://slack.com/intl/en-gb/help/articles/202009646-Notify-a-channel-or-workspace#what-to-expect

**Comment by ravgeetdhillon** [comment]
Hey @drewhemm, would #16 help you?

**Comment by ravgeetdhillon** [comment]
@drewhemm Were you able to solve your issue?

**Comment by ravgeetdhillon** [comment]
@drewhemm Closing this issue for now but feel free to open it in case your problem hasn't been solved.
