### ISSUE TITLE
Please add support for Windows/Mac OS X

### ISSUE THREAD

**Issue by Jnesselr** [ravsamhq/notify-slack-action#46]
This seems like an awesome utility, but doesn't seem to work at all on Windows/Mac OS X because I'm getting the error: Error: Container action is only supported on Linux

**Comment by ravgeetdhillon** [comment]
@Jnesselr You are right. Currently, the action is only supported for the Linux environment as it uses Docker. In the coming few weeks, I will rewrite the existing action in Javascript, which would make it multi-platform and speed up the build. You can track the progress here (#38).

**Comment by ravgeetdhillon** [comment]
@Jnesselr To get rid of the slow build speeds of Docker and to support multiple build environments, we have released **v2** which is written in Typescript. See [this comment](https://github.com/ravsamhq/notify-slack-action/issues/38#issuecomment-1219417190) for more information.
