### ISSUE TITLE
Improve message, p2

### ISSUE THREAD

**Issue by andrii29** [ravsamhq/notify-slack-action#5]
Hello,
please improve this action a little bit:
- allow to mention teams (https://stackoverflow.com/questions/54284389/mention-users-group-via-slack-api)
- put mentions in a new line of message (look's much better than one long lone)
-  fix empty mentions
Now without specify mention and mention_when I will get message like this
https://user-images.githubusercontent.com/31315876/114349748-f8ef3200-9b70-11eb-96ea-08c71681a19d.png
consider update if statement https://github.com/ravsamhq/notify-slack-action/blob/master/main.py#L98
`and mention != ''`

Regards,
Andrii

**Comment by ravgeetdhillon** [comment]
This issue has been resolved in release [1.3.0](https://github.com/ravsamhq/notify-slack-action/releases/tag/1.3.0).
