### ISSUE TITLE
Request: Add "skipped" status

### ISSUE THREAD

**Issue by rdhar** [ravsamhq/notify-slack-action#73]
Hi @ravgeetdhillon, many thanks for sharing this super-useful GitHub action with us! 

On the `job.status`, it looks like "skipped" status has been missed out as a potential option. "skipped" is a valid, documented result/conclusion for both [`jobs`](https://docs.github.com/en/actions/learn-github-actions/contexts#jobs-context) and [`steps`](https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context) contexts so it'd be really appreciated if it could be captured similar to "cancelled". 

It might seem odd, but I leverage notify-slack-action@v2 as the last in a chain of jobs which outputs their overall status like shown below. So that how's we can potentially end up with the "skipped" status needing to notify Slack. 

```yml
status: ${{ needs.build.result || needs.scan.result || needs.deploy.result }}
```

Cheers,
Rishav

**Comment by ravgeetdhillon** [comment]
@rdhar This issue has been fixed in the release [v2.3.0](https://github.com/ravsamhq/notify-slack-action/releases/tag/2.3.0). Let me know if you are happy with the new changes.
