### ISSUE TITLE
mac runner not able to parse workflow_url 

### ISSUE THREAD

**Issue by renperez** [ravsamhq/notify-slack-action#74]
workflow url is not working for some reason.

```
"Github Action <{workflow_url}|{workflow}> workflow has {status_message}"
```
this is the message i get from slack:
Github Action <|Smoke Test> workflow has passed

**Comment by ravgeetdhillon** [comment]
@renperez In the README, it is mentioned:

> In order to use `{workflow_url}`, specify the `token` input as `token: ${{ secrets.GITHUB_TOKEN }}`.

So, make sure you have setup the action correctly. Let me know if this works for you.

**Comment by renperez** [comment]
@ravgeetdhillon thank you. yeah looks like the token i was using was the culprit. closing this :)
