### ISSUE TITLE
Intermittent missing SLACK_WEBHOOK_URL

### ISSUE THREAD

**Issue by madhavajay** [ravsamhq/notify-slack-action#80]
Sometimes we get this error:
```
Error: No SLACK_WEBHOOK_URL provided
```

<img width="1074" alt="Screen Shot 2022-11-30 at 2 57 38 pm" src="https://user-images.githubusercontent.com/2882739/204711137-e119e026-cc6b-4c44-9bd3-02bc6c62d262.png">

https://github.com/OpenMined/PySyft/actions/runs/3579463590/jobs/6022166889

However other times it's no issue.
<img width="556" alt="Screen Shot 2022-11-30 at 2 56 49 pm" src="https://user-images.githubusercontent.com/2882739/204711169-16f63251-0a07-4bb4-befd-dcdc4ac44230.png">

Any ideas why?

**Comment by SPConrad** [comment]
Also experiencing this but only for one repository, I have two other repos that are working fine. I have two macOS runners and one `ubuntu-latest` runner that work fine, and one `ubuntu-latest` runner that fails. The `notify-slack-action` step is identical for each repo. 

Unsure what information might be relevant but happy to provide what I can

**Comment by kwolf-experian** [comment]
We're seeing this as well, but I think we're only seeing it on pull requests created by dependabot.  Maybe these PR's don't have access to repository secrets?

**Comment by ravgeetdhillon** [comment]
This is something that is not related to this action, so I am closing this issue.
